### ISSUE TITLE
Compatibility with Magento 2.4.3: Could not find a matching version of package magento/billie-payment-method

### ISSUE THREAD

**Issue by kisroman** [ozean12/magento2#1]
Magento version 2.4.3

1. composer config repositories.billie git git@github.com:ozean12/magento2.git
2. composer require magento/billie-payment-method

### Expected result:
Module is installed.

### Actual result: 
 [InvalidArgumentException]                                                                                                                                                                             
  Could not find a matching version of package magento/billie-payment-method. Check the package spelling, your version constraint and that the package is available in a stability which matches your m  
  inimum-stability (dev).

**Comment by rommelfreddy** [comment]
Hello @kisroman 
the extension is currently not compatible with Magento 2.4.x.

i will create an internal ticket, and will update this issue, if there is a new release. 
You can also watch the repo to get the latest updates. 

With the next release, you will be able to install it directly without defining a  repo

**Comment by kisroman** [comment]
Hello @rommelfreddy, do you have some date when new version of extension will be available and compatible with Magento 2.4? Thanks.

**Comment by rommelfreddy** [comment]
Hello @kisroman 

i am so sorry for the late response. 

Billie has testet the plugin the last days, and I got the OK to create a release of the new SDK integration. With that you also got the compatibility for Magento 2.4.x.

Please close the issue, if there are no issues anymore.
